#!/usr/bin/env bash

sudo echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	trap "echo I hate the kill command" SIGTERM
	trap "echo Y U no love me?!" SIGINT

	trap "sudo rm /var/run/myscript.pid ; kill $$" SIGQUIT
	trap "sudo rm /var/run/myscript.pid ; kill $$" SIGTERM

	sleep 2
done