#!/usr/bin/env bash

# create PID file
echo "$$" > /var/run/myscript.pid

# handle signal conditions
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; kill -15 "$$"' SIGQUIT SIGTERM

# continuoudly display message
while true
do
    echo "To infinity and beyond"
    sleep 2
done
