#!/usr/bin/env bash
# print the contents of the current directory
#+ print characters in name only after the first "-"

for file in ./*
do
	# print file names
	echo "$file" | cut -d '-' -f2- | cut -d '/' -f2-
done